In [2]:
import pandas as pd
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
df = pd.read_csv(filename)

In [4]:
df

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

# **Quiz on DataFrame**

In [23]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
df = pd.read_csv(filename)
df

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

Use a variable q to store the column Price as a dataframe

In [25]:
q = df[['Price']]
q

   Price
0    800
1    600
2    150
3      2
4    300

Assign the variable q to the dataframe that is made up of the column Product and Category:

In [26]:
q = df[['Product','Category']]
q

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

Access the 2nd row and the 3rd column of df:

In [40]:
a = df.iloc[1,2]
a

'Electronics'

Use the following list to convert the dataframe index df to characters and assign it to df_new; find the element corresponding to the row index a and column 'CustomerCity'. Then select the rows a through d for the column 'CustomerCity'

new_index=['a','b','c','d','e']

In [56]:
new_index=['a','b','c','d','e']
df_new= df.copy() 
df_new.index = new_index
df_new

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
a,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
b,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
c,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
d,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
e,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [59]:
df_new.loc['a','CustomerCity']

'New York'

In [62]:
df_new.loc['d':'e', 'CustomerCity']

d    Houston
e      Miami
Name: CustomerCity, dtype: object